# Generated by Django 5.2 on 2025-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='invite_code',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Код приглашения'),
        ),
    ]
