# Generated by Django 5.2 on 2025-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_projectuser_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка приглашения'),
        ),
    ]
