# Generated by Django 5.2 on 2025-04-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_alter_project_created_at_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Создатель'), ('admin', 'Администратор')], default='creator', max_length=100, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
