# Generated by Django 5.2 on 2025-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_alter_projectuser_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Создатель'), ('ADMIN', 'Администратор')], default='CREATOR', max_length=100, verbose_name='Роль'),
        ),
    ]
