services:
  postgres:
    image: postgres:15-alpine
    container_name: dev_diplom_postgres
    env_file:
      - ./postgres.env
    ports:
      - "127.0.0.1:25000:5432"
    volumes:
      - diplom_pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  backend:
    build: ./backend
    container_name: dev_diplom_backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    env_file:
      - ./postgres.env
      - ./backend/.env
    ports:
      - "127.0.0.1:25001:8000"
    volumes:
      - ./backend:/app
      - ./content:/content
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
  
  frontend:
    build: ./frontend
    container_name: dev_diplom_frontend
    ports:
      - "127.0.0.1:25002:5173"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/eslint.config.js:/app/eslint.config.js
      - ./frontend/vite.config.js:/app/vite.config.js
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 1024M
  
  adminer:
    image: adminer
    container_name: dev_diplom_adminer
    ports:
      - "127.0.0.1:25003:8080"
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M

volumes:
  diplom_pgdata:
