# Generated by Django 5.2 on 2025-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_show_in_kanban',
            field=models.BooleanField(default=True, verbose_name='Показывать в канбане'),
        ),
    ]
