# Generated by Django 5.1.4 on 2025-01-11 18:48

import confirm_manager.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=confirm_manager.models.get_random_code, max_length=6, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_%(class)s', to='user_manager.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код активации Email',
                'verbose_name_plural': 'Коды активации Email',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CodeRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=confirm_manager.models.get_random_code, max_length=6, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_%(class)s', to='user_manager.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код сброса пароля',
                'verbose_name_plural': 'Коды сброса пароля',
                'ordering': ['created'],
            },
        ),
    ]
