# Generated by Django 5.2 on 2025-04-28 21:45

import note_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=note_manager.models.upload_to, verbose_name='Изображение'),
        ),
    ]
